### PR TITLE
Propagate master to develop

### PR DESCRIPTION
**Pull request by HuFangshuai**
Merge master into develop branch prepare to merge 6.9.x-release into develop.

### CODE REVIEW

**Comment by jiancchen** [comment]
@HuFangshuai can you pull in the latest, admob, i'll review asap, thanks

**Comment by HuFangshuai** [comment]
> @HuFangshuai can you pull in the latest, admob, i'll review asap, thanks

Thank @jiancchen, have updated the lastest code.

**Review by jiancchen — APPROVED** [review]

**Comment by HuFangshuai** [comment]
For AdMob propagate PRs we must use `Rebase and merge` option to merge the pr, but develop branch currently can't be rebased with master branch due to we not allowed force-push to develop.

**Comment by HuFangshuai** [comment]
For AdMob propagate PRs we must use Rebase and merge option to merge the pr, but develop branch currently can't be rebased with upstream/master branch due to we not allowed force-push to develop.

**Pull request closed without merging**
