### PR TITLE
[AND-2743] Use sequential downloading epic

### PR DESCRIPTION
**Pull request by alexander-gubov**

### CODE REVIEW

**Comment by HuFangshuai** [comment]
Seq. Download as one sdk 6.7.x feature, so this PR target branch should be changed to sdk6.7.x

**Comment by HuFangshuai** [comment]
I saw some event handling callbacks changes here and there's already one PR: https://github.com/Vungle/googleads-mobile-android-mediation/pull/33
to handle it.

**Comment by alexander-gubov** [comment]
> I saw some event handling callbacks changes here and there's already one PR: #33
> to handle it.

Yes, I left them empty to resolve conflicts later, depending on the merge order.

**Comment by HuFangshuai** [comment]
When you merge this PR prefer to use `Rebase and merge` option because AdMob CLA does not allow commits history contains internal merge commit.

**Comment by alexander-gubov** [comment]
> When you merge this PR prefer to use `Rebase and merge` option because AdMob CLA does not allow commits history contains internal merge commit.

It's more for testing of fixed bugs, most probably it will be closed after we will have final decisions on AND-2743

**Pull request closed without merging**
